[package]
name = "aoc-main"
description = "A macro which defines a handful main for the Advent of Code"
version = "0.2.0"
authors = ["Rémi Dupré <r.dupre@qwant.com>"]
repository = "https://github.com/remi-dupre/aoc"
license = "Apache-2.0"
readme = "README.md"
keywords = ["advent", "aoc", "macro"]
edition = "2018"

[dependencies]
attohttpc = { version = "0.16.0", default_features = false, features = ["tls"] }
clap = "3.0.0-beta.2"
colored = "2.0.0"
criterion = "0.3.3"
