[package]
name = "aoc"
version = "0.1.0"
authors = ["Rémi Dupré <r.dupre@qwant.com>"]
edition = "2018"

[dependencies]
attohttpc = { version = "0.16.0", default_features = false, features = ["tls"] }
clap = "3.0.0-beta.2"
